@startuml
title Діаграма активностей - сюжет фільму "Назад у майбутнє" (1985)

start

:Марті Макфлай зустрічається\nз доком Брауном у 1985 році;
:Док демонструє автомобіль DeLorean,\nперетворений на машину часу;

if (Лівійські терористи з'являються\nі стріляють у дока?) then (так)
  :Марті тікає на DeLorean\nі випадково активує\nподорож у часі;
  :Марті потрапляє в 1955 рік;
else (ні)
  stop
endif

:Марті випадково заважає\nзнайомству своїх майбутніх\nбатьків (Джорджа і Лоррейн);
note right
  <b>Точка розгалуження сюжету:</b>
  ця подія - "тригер", що запускає
  основний конфлікт фільму.
end note

:Лоррейн закохується в Марті\nзамість Джорджа - часова лінія\nпочинає змінюватися;
:Марті бачить, що сам\nпочинає "зникати" з фотографії;

repeat
  :Марті шукає дока Брауна\nверсії 1955 року;
  :Просить допомогти повернутися\nу 1985 та виправити\nзнайомство батьків;
  :Розробляють план:\nзалучити блискавку до\nгодинникової вежі для\nзаряду машини часу;

  :Марті намагається\nзвести Джорджа й Лоррейн\nзаново (танці на балу\n"Під чарами моря");

  if (Джордж проявляє сміливість\nі захищає Лоррейн від Біффа?) then (так)
    :Батьки закохуються одне\nв одного природним шляхом;
    :Часова лінія\nпочинає відновлюватися;
    :Марті перестає зникати\nз фотографії;
    break
  else (ні)
    :План провалюється,\nчасова лінія залишається\nпід загрозою;
  endif
repeat while (часова лінія ще не\nвідновлена і час ще є?) is (так)
->ні (час вичерпано);

:Гроза наближається до\nгодинникової вежі;
:Марті готує DeLorean\nдо стрибка назад у 1985,\nвикористовуючи енергію блискавки;

if (Зв'язок проводу до\nDeLorean розірвався\nв останню мить?) then (так)
  :Док лагодить з'єднання\nта ризикує життям\nпід ударом блискавки;
endif

:Блискавка влучає в годинникову\nвежу - DeLorean розганяється\nдо 88 миль/год;
:Марті повертається\nу змінене сьогодення (1985);

:Марті виявляє, що його родина\nстала успішнішою та щасливішою\nзавдяки зміненій часовій лінії;
:Док Браун (живий, з 1985) приїжджає\nна вдосконаленому DeLorean\nз майбутнього;

:Док кличе Марті й його дівчину\nу нову подорож - "Вам треба\nпобачити, що буде з вашими дітьми!";
note right
  <b>Чому ця структура зручна для UML:</b> сюжет має чітку причинно-
  наслідкову послідовність (тригер -> конфлікт -> повторювані спроби
  його розв'язати -> кульмінація -> розв'язка), природні точки
  розгалуження (рішення персонажів) та цикл "спроба-невдача-нова
  спроба", що ідеально відображається конструкціями if/else та
  repeat/while діаграми активностей UML.
end note

stop

@enduml
